# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Base Box
  config.vm.box = "ubuntu/trusty64"

  # VirtualBox settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
  end
  config.vm.provision "shell", path: "./provision/install_swift.sh", privileged: false
  config.vm.provision "shell", path: "./provision/install_x.sh"
  config.vm.provision "shell", path: "./provision/install_firefox.sh"
  config.vm.provision "shell", path: "./provision/install_atom.sh", privileged: false
  config.vm.provision "shell", inline: "reboot"
end
